---
title: "Measuring Physical Activity in Older Adults through Data Donation: Consent Rates, Donation Success, & Bias"
author: "Florian Keusch"
date: "2025-08-20"
output:
  html_document:
    df_print: paged
  pdf_document: default
subtitle: Data preparation
---

Data can be found at https://doi.org/10.57990/5ez3-br33

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "U:\\Mannheim\\Grants\\NIMLAS\\Data")
```

# Install and load required packages
```{r, warning=FALSE, message=FALSE}
if (!require(haven)) install.packages("haven")
library(haven)

if (!require(dplyr)) install.packages("dplyr")
library(dplyr)

if (!require(psych)) install.packages("psych")
library(psych)

if (!require(readr)) install.packages("readr")
library(readr)
```

# Load data
```{r}
df_survey <- read_sav("L_NIMLAS_1.0p.sav") 
df_port <- read_sav("L_NIMLAS_PortVariables_1.0p.sav")
```

# Merge data
```{r}
df <- merge(df_survey, df_port, by = "nomem_encr")
```

# Sociodemographics
```{r}
## Gender
df <- df %>%
  mutate(gender = factor(
    case_when((geslacht == 1) ~ "Male",
              (geslacht == 2) ~ "Female",
              (geslacht == 3) ~ "Other"
    ),
    levels = c("Female", "Male", "Other")
  ))

summary(df$gender)

## Age
summary(df$gebjaar)

df <- df %>%
  mutate(age = as.numeric(2023 - gebjaar))

summary(df$age)
hist(df$age)

df <- df %>%
  mutate(age_groups = factor(
    case_when((age < 55) ~ "50-54 years",
              (age >= 55 &
                 age < 60) ~ "55-59 years",
              (age >= 60 &
                 age < 65) ~ "60-64 years",
              (age >= 65 &
                 age < 70) ~ "65-69 years",
              (age >= 70 &
                 age < 75) ~ "70-74 years",
              (age >= 75 &
                 age < 80) ~ "75-79 years",
              (age >= 80) ~ "80 years or older"
    )
  ))

summary(df$age_groups)

## HH size
summary(df$aantalhh)

df <- df %>%
  mutate(hh_size = factor(
    case_when((aantalhh == 1) ~ "One person HH",
              (aantalhh == 2) ~ "Two person HH",
              (aantalhh > 2) ~ "Three and more person HH"
    ),
    levels = c("One person HH", "Two person HH",
               "Three and more person HH")
  ))

summary(df$hh_size)

## Urabnicity
summary(df$sted)

df <- df %>%
  mutate(urban = factor(
    case_when((sted == 1) ~ "Very strongly urban",
              (sted == 2) ~ "Strongly urban",
              (sted == 3) ~ "Moderately urban",
              (sted == 4) ~ "Little urban",
              (sted == 5) ~ "Not urban",
              .default = NA
    ),
    levels = c(
      "Not urban",
      "Little urban",
      "Moderately urban",
      "Strongly urban",
      "Very strongly urban"
    )
  ))

summary(df$urban)

## Employment status
summary(df$belbezig)

### Create employment variable with only three categories
df <- df %>%
  mutate(employ3 = factor(
    case_when((belbezig >= 1 & belbezig <= 3) ~ "Employed for pay",
              ((belbezig >= 4 &
                 belbezig <= 7) |
                 belbezig == 9 |
                 belbezig == 10)  ~ "Unemployed/Retired/Disabled",
              ((belbezig == 8) |
                 (belbezig >= 11 & belbezig <= 13)) ~
                "Unpaid work, incl. housework",
              .default = NA
    ),
    levels = c(
      "Employed for pay",
      "Unpaid work, incl. housework",
      "Unemployed/Retired/Disabled"
    )
  ))

summary(df$employ3)

## Personal net income
summary(df$nettocat)
hist(df$nettocat)

df <- df %>%
  mutate(income = factor(
    case_when((nettocat == 0 | (is.na(nettocat))) ~ "No income/NA",
              (nettocat == 1 |
                 nettocat == 2) ~ "EUR 1000 or less",
              (nettocat == 3) ~ "EUR 1001 to EUR 1500",
              (nettocat == 4) ~ "EUR 1501 to EUR 2000",
              (nettocat == 5) ~ "EUR 2001 to EUR 2500",
              (nettocat == 6) ~ "EUR 2501 to EUR 3000",
              (nettocat >= 7 &
                 nettocat <= 12) ~ "More than EUR 3000"
    ),
    levels = c(
      "EUR 1000 or less",
      "EUR 1001 to EUR 1500",
      "EUR 1501 to EUR 2000",
      "EUR 2001 to EUR 2500",
      "EUR 2501 to EUR 3000",
      "More than EUR 3000",
      "No income/NA"
    )
  ))

summary(df$income)

## Education
summary(df$oplcat)
hist(df$oplcat)

### Create education variable with only three categories
df <- df %>%
  mutate(educ3 = factor(
    case_when((oplcat == 1 | oplcat == 2) ~ "Low",
              (oplcat == 3 |
                 oplcat == 4) ~ "Medium",
              (oplcat == 5 |
                 oplcat == 6) ~ "High",
              .default = NA
    ),
    levels = c("Low", "Medium", "High")
  ))
summary(df$educ3)
```

# Health
```{r}
## Self-rated health
summary(as.factor(df$Q1))

### Rename and label SRH variable
df <- df %>%
  mutate(srh5 = factor(
    case_when(Q1 == 1 ~ "Bad",
              Q1 == 2 ~ "Moderate",
              Q1 == 3 ~ "Good",
              Q1 == 4 ~ "Very good",
              Q1 == 5 ~ "Excellent",
              .default = NA
    ),
    levels = c("Bad",
               "Moderate",
               "Good",
               "Very good",
               "Excellent")
  ))

summary(df$srh5)

### Create SRH variable with only three categories (i.e., combining "Bad" and "Moderate" and "Very good" and "Excellent")
df <- df %>%
  mutate(srh3 = factor(
    case_when((Q1 == 1 | Q1 == 2) ~ "Bad/Moderate",
              (Q1 == 3) ~ "Good",
              (Q1 == 4 | Q1 == 5) ~ "Very good/Excellent",
              .default = NA
    ),
    levels = c("Bad/Moderate", "Good", "Very good/Excellent")
  ))

summary(df$srh3)

## Limitations in activities
summary(df$Q2)
summary(df$Q3)
summary(df$Q4)

### EFA for limits (Tables B7-B10)
df_lim <- df %>% 
  select(Q2:Q4)
colSums(is.na(df_lim))
psych::alpha(df_lim)
KMO(df_lim)
cortest.bartlett(df_lim)
ev <- eigen(cor(df_lim))
ev$values
scree(df_lim, pc=FALSE)
fit <- factanal(df_lim, 1, rotation="varimax")
print(fit, digits=2, cutoff=0.3, sort=TRUE)

### Create Limits Index
df <- df %>% 
  mutate(lim_index = ((Q2 + Q3 + Q4)/3))

summary(df$lim_index)
hist(df$lim_index)

### Tertile split Limits index
df <- df %>%
  mutate(tertile_lim = ntile(lim_index, 3),
         lim_ter = case_when(
           tertile_lim == 1 ~ "low",
           tertile_lim == 2 ~ "medium",
           tertile_lim == 3 ~ "high"
         ),
         lim_ter = factor(lim_ter,
                           levels = c("low", "medium", "high")))

summary(df$lim_ter)

### Rename and label limitations variables
#### Build function for recoding variables 
create_factor_variable_act5 <-
  function(df, column, new_column_name) {
    df <- df %>%
      dplyr::mutate({
        {
          new_column_name
        }
      } := factor(
        case_when(.data[[column]] == 1 ~ "Not at all",
                  .data[[column]] == 2 ~ "Hardly",
                  .data[[column]] == 3 ~ "A bit",
                  .data[[column]] == 4 ~ "Quite a lot",
                  .data[[column]] >= 5 ~ "Very much",
                  .default = NA
        ),
        levels = c("Not at all",
                   "Hardly",
                   "A bit",
                   "Quite a lot",
                   "Very much")
      ))
    return(df)
  }

#### Recode limitation variables
df <- create_factor_variable_act5(df, "Q2", "lim_daily_act5")
df <-
  create_factor_variable_act5(df, "Q3", "lim_social_act5")
df <- create_factor_variable_act5(df, "Q4", "lim_work5")

summary(df$lim_daily_act5)
summary(df$lim_social_act5)
summary(df$lim_work5)

## Difficulties performing certain activities
summary(df$Q5_1)
summary(df$Q5_2)
summary(df$Q5_3)
summary(df$Q5_4)
summary(df$Q5_5)
summary(df$Q5_6)
summary(df$Q5_7)
summary(df$Q5_8)
summary(df$Q5_9)
summary(df$Q5_10)

### EFA for difficulties (B11-B14)
df_diff <- df %>% 
  select(Q5_1:Q5_10)
colSums(is.na(df_diff))
df_diff <- df_diff %>% 
  filter(!is.na(Q5_1))
colSums(is.na(df_diff))
psych::alpha(df_diff)
KMO(df_diff)
cortest.bartlett(df_diff)
ev <- eigen(cor(df_diff))
ev$values
scree(df_diff, pc=FALSE)
fit <- factanal(df_diff, 1, rotation="varimax")
print(fit, digits=2, cutoff=0.3)

### Create difficulties Index
df <- df %>% 
  mutate(diff_index = ((Q5_1 + Q5_2 + Q5_3 + Q5_4 + Q5_5 +
                         Q5_6 + Q5_7 + Q5_8 + Q5_9 + Q5_10)/10))

summary(df$diff_index)
hist(df$diff_index)

### Tertile split Difficulties index
df <- df %>%
  mutate(tertile_diff = ntile(diff_index, 3),
         diff_ter = case_when(
           tertile_diff == 1 ~ "low",
           tertile_diff == 2 ~ "medium",
           tertile_diff == 3 ~ "high"
         ),
         diff_ter = factor(diff_ter,
                           levels = c("low", "medium", "high")))

summary(df$diff_ter)

### Rename and label limitations variables
#### Build function for recoding variables
create_factor_variable_trouble5 <-
  function(df, column, new_column_name) {
    df <- df %>%
      dplyr::mutate({
        {
          new_column_name
        }
      } := factor(
        case_when(.data[[column]] == 1 ~ "Without any difficulties",
                  .data[[column]] == 2 ~ "With some difficulties",
                  .data[[column]] == 3 ~ "With a lot of difficulties",
                  .data[[column]] == 4 ~ "Only with an aid or the help of others",
                  .data[[column]] == 5 ~ "Not",
                  .default = NA
        ),
        levels = c(
          "Without any difficulties",
          "With some difficulties",
          "With a lot of difficulties",
          "Only with an aid or the help of others",
          "Not"
          )
      ))
    return(df)
  }

#### Recode variables
df <- create_factor_variable_trouble5(df, "Q5_1", "diff_100m5")
df <- create_factor_variable_trouble5(df, "Q5_2", "diff_sitting5")
df <- create_factor_variable_trouble5(df, "Q5_3", "diff_getup5")
df <- create_factor_variable_trouble5(df, "Q5_4", "diff_multflights5")
df <- create_factor_variable_trouble5(df, "Q5_5", "diff_oneflight5")
df <- create_factor_variable_trouble5(df, "Q5_6", "diff_allfours5")
df <-
  create_factor_variable_trouble5(df, "Q5_7", "diff_aboveshoulder5")
df <-
  create_factor_variable_trouble5(df, "Q5_8", "diff_movingobjects5")
df <- create_factor_variable_trouble5(df, "Q5_9", "diff_lifting5")
df <- create_factor_variable_trouble5(df, "Q5_10", "diff_pickup5")

summary(df$diff_100m5)
summary(df$diff_sitting5)
summary(df$diff_getup5)
summary(df$diff_multflights5)
summary(df$diff_oneflight5)
summary(df$diff_allfours5)
summary(df$diff_aboveshoulder5)
summary(df$diff_movingobjects5)
summary(df$diff_lifting5)
summary(df$diff_pickup5)

## Chronic illness
summary(df$Q6)

### Build function for recoding 1/2 variables into yes/no variables
create_factor_variable_noyes <-
  function(df, column, new_column_name) {
    df <- df %>%
      dplyr::mutate({
        {
          new_column_name
        }
      } := factor(
        case_when((.data[[column]] == 1) ~ "Yes",
                  (.data[[column]] == 2) ~ "No",
                  .default = NA
        )
      ))
    return(df)
  }

### Recode chronic illness variable
df <- create_factor_variable_noyes(df, "Q6", "chronic")

summary(df$chronic)

## BMI
### Height
summary(df$Q21)
hist(df$Q21)

#### Renaming variable and setting cases <100cm to NA
df <- df %>%
  mutate(height = case_when((Q21 > 100) ~ Q21 / 100, 
                            .default = NA))

summary(df$height)
hist(df$height)

### Weight
summary(df$Q22)
hist(df$Q22)

#### Renaming variable and setting cases <40kg and >200kg to NA
df <- df %>%
  mutate(weight = case_when((Q22 >= 40 & Q22 <= 200) ~ Q22, 
                            .default = NA))

summary(df$weight)
hist(df$weight)

### Create BMI variable
df <- df %>%
  mutate(bmi = weight / (height ^ 2))

summary(df$bmi)
hist(df$bmi)

### Create categorical BMI variable with four groups
df <- df %>%
  mutate(bmi4 = factor(
    case_when(bmi < 18.5 ~ "Underweight",
              (bmi >= 18.5 &  bmi < 25) ~ "Healthy weight",
              (bmi >= 25 &  bmi < 30) ~ "Overweight",
              bmi >= 30 ~ "Obesity",
              .default = NA
    ),
    levels = c("Underweight",
               "Healthy weight",
               "Overweight",
               "Obesity")
  ))

summary(df$bmi4)

### Create categorical BMI variable with three groups
df <- df %>%
  mutate(bmi3 = factor(
    case_when(bmi < 25 ~ "Underweight/Healthy weight",
              (bmi >= 25 &  bmi < 30) ~ "Overweight",
              bmi >= 30 ~ "Obesity",
              .default = NA
    ),
    levels = c("Underweight/Healthy weight",
               "Overweight",
               "Obesity")
  ))
summary(df$bmi3)
```

# Physical activity
```{r}
## No of days with strenuous physical activity
summary(df$Q7)
hist(df$Q7)

df <- df %>% 
  mutate(days_stren_physical_act_num = Q7)

### Tertile split No of days with strenuous physical activity
df <- df %>%
  mutate(tertile_days_stren_physical_act = ntile(days_stren_physical_act_num, 3),
         days_stren_physical_act_ter = case_when(
           tertile_days_stren_physical_act == 1 ~ "low",
           tertile_days_stren_physical_act == 2 ~ "medium",
           tertile_days_stren_physical_act == 3 ~ "high"
         ),
         days_stren_physical_act_ter = factor(days_stren_physical_act_ter,
                                              levels = c("low", "medium", "high")))

summary(df$days_stren_physical_act_ter)

## No of days with moderate physical activity
summary(df$Q9)
hist(df$Q9)

df <- df %>% 
  mutate(days_mod_physical_act_num = Q9)

### Tertile split No of days with moderate physical activity
df <- df %>%
  mutate(tertile_days_mod_physical_act = ntile(days_mod_physical_act_num, 3),
         days_mod_physical_act_ter = case_when(
           tertile_days_mod_physical_act == 1 ~ "low",
           tertile_days_mod_physical_act == 2 ~ "medium",
           tertile_days_mod_physical_act == 3 ~ "high"
         ),
         days_mod_physical_act_ter = factor(days_mod_physical_act_ter,
                                            levels = c("low", "medium", "high")))

summary(df$days_stren_physical_act_ter)

## No of days with walking
summary(df$Q11)
hist(df$Q11)

df <- df %>% 
  mutate(days_walking_num = Q11)

### Tertile split No of days with walking
df <- df %>%
  mutate(tertile_days_walking = ntile(days_walking_num, 3),
         days_walking_ter = case_when(
           tertile_days_walking == 1 ~ "low",
           tertile_days_walking == 2 ~ "medium",
           tertile_days_walking == 3 ~ "high"
         ),
         days_walking_ter = factor(days_walking_ter,
                                   levels = c("low", "medium", "high")))

summary(df$days_walking_ter)

## No of days with biking
summary(df$Q13)
hist(df$Q13)

df <- df %>% 
  mutate(days_biking_num = Q13)

### Tertile split No of days with biking
df <- df %>%
  mutate(tertile_days_biking = ntile(days_biking_num, 3),
         days_biking_ter = case_when(
           tertile_days_biking == 1 ~ "low",
           tertile_days_biking == 2 ~ "medium",
           tertile_days_biking == 3 ~ "high"
         ),
         days_biking_ter = factor(days_biking_ter,
                                  levels = c("low", "medium", "high")))

summary(df$days_biking_ter)

## No of days with running
summary(df$Q15)
hist(df$Q15)

df <- df %>% 
  mutate(days_running_num = Q15)

### Tertile split No of days with running
df <- df %>%
  mutate(tertile_days_running = ntile(days_running_num, 3),
         days_running_ter = case_when(
           tertile_days_running == 1 ~ "low",
           tertile_days_running == 2 ~ "medium",
           tertile_days_running == 3 ~ "high"
         ),
         days_running_ter = factor(days_running_ter,
                                   levels = c("low", "medium", "high")))

summary(df$days_running_ter)

## Time sedentary
summary(df$Q17_1)
summary(df$Q17_2)

df <- df %>% 
  mutate(min_sedentary = Q17_1*60 + Q17_2)

summary(df$min_sedentary)
hist(df$min_sedentary)

df <- df %>% 
  mutate(h_sedentary = min_sedentary/60)

summary(df$h_sedentary)
hist(df$h_sedentary)

### Tertile split Time sedentary
df <- df %>%
  mutate(tertile_h_sedentary = ntile(h_sedentary, 3),
         h_sedentary_ter = case_when(
           tertile_h_sedentary == 1 ~ "low",
           tertile_h_sedentary == 2 ~ "medium",
           tertile_h_sedentary == 3 ~ "high"
         ),
         h_sedentary_ter = factor(h_sedentary_ter,
                                  levels = c("low", "medium", "high")))

summary(df$h_sedentary_ter)

## Outside yesterday
summary(df$Q18)
df <- create_factor_variable_noyes(df, "Q18", "outdoors")

summary(df$outdoors)
```

# Smartphone-related characteristics
```{r}
## Smartphone ownership
summary(df$Q23)
summary(df$Q23twijfel)

df <- df %>%
  mutate(smart_own = factor(
    case_when((Q23 == 1 | Q23twijfel == 1) ~ "Owns smartphone",
              (Q23 >= 2 |
                 Q23twijfel == 2) ~ "Does not own smartphone",
              .default = NA
    )
  ))

summary(df$smart_own)

## OS
summary(df$Q24_1)

df <- df %>%
  mutate(smart_os = factor(
    case_when((Q24_1 == 1) ~ "iPhone",
              (Q24_1 == 2) ~ "Android",
              (Q24_1 >= 3 &
                 Q24_1 <= 6) ~ "Other",
              .default = NA
    ),
    levels = c("iPhone", "Android", "Other")
  ))

summary(df$smart_os)

### Owns iPhone/Android phone (prerequisite for data donation)
df <- df %>%
  mutate(smart_iphoneandroid = factor(
    case_when((smart_os == "iPhone" |
                 smart_os == "Android") ~ "iPhone or Android",
              (smart_os == "Other" | (is.na(smart_os))) ~ "Other/No smartphone"
    ),
    levels = c("Other/No smartphone", "iPhone or Android")
  ))

summary(df$smart_iphoneandroid)

## Samsung
summary(df$Q24_2)

df <- df %>%
  mutate(smart_samsung = factor(
    case_when((Q24_2 == 1) ~ "Samsung phone",
              (Q24_2 == 2) ~ "Other Android phone",
              .default = NA
    ),
    levels = c("Samsung phone", "Other Android phone")
  ))

summary(df$smart_samsung)

## Samsung Health user
summary(df$Q24_3)

df <- df %>%
  mutate(smart_samsunghealth = factor(
    case_when((Q24_3 == 1) ~ "Uses Samsung Health app",
              (Q24_3 == 2) ~ "Does not use Samsung Health app",
              .default = NA
    ),
    levels = c("Uses Samsung Health app",
               "Does not use Samsung Health app")
  ))

summary(df$smart_samsunghealth)

## Smartphone activities
summary(df$Q25a)
summary(df$Q25b)
summary(df$Q25c)
summary(df$Q25d)
summary(df$Q25e)
summary(df$Q25f)
summary(df$Q25g)
summary(df$Q25h)
summary(df$Q25i)
summary(df$Q25j)
summary(df$Q25k)
summary(df$Q25l)
summary(df$Q25m)
summary(df$Q25n)
summary(df$Q25o)

df <-
  create_factor_variable_noyes(df, "Q25a", "smart_act_messaging")
df <- create_factor_variable_noyes(df, "Q25b", "smart_act_websites")
df <- create_factor_variable_noyes(df, "Q25c", "smart_act_email")
df <- create_factor_variable_noyes(df, "Q25d", "smart_act_photo")
df <-
  create_factor_variable_noyes(df, "Q25e", "smart_act_makingvideo")
df <-
  create_factor_variable_noyes(df, "Q25f", "smart_act_smpassive")
df <- create_factor_variable_noyes(df, "Q25g", "smart_act_smactive")
df <- create_factor_variable_noyes(df, "Q25h", "smart_act_shopping")
df <- create_factor_variable_noyes(df, "Q25i", "smart_act_banking")
df <- create_factor_variable_noyes(df, "Q25j", "smart_act_newapps")
df <- create_factor_variable_noyes(df, "Q25k", "smart_act_gps")
df <-
  create_factor_variable_noyes(df, "Q25l", "smart_act_bluetooth")
df <- create_factor_variable_noyes(df, "Q25m", "smart_act_calling")
df <- create_factor_variable_noyes(df, "Q25n", "smart_act_games")
df <-
  create_factor_variable_noyes(df, "Q25o", "smart_act_streaming")

summary(df$smart_act_messaging)
summary(df$smart_act_websites)
summary(df$smart_act_email)
summary(df$smart_act_photo)
summary(df$smart_act_makingvideo)
summary(df$smart_act_smpassive)
summary(df$smart_act_smactive)
summary(df$smart_act_shopping)
summary(df$smart_act_banking)
summary(df$smart_act_newapps)
summary(df$smart_act_gps)
summary(df$smart_act_bluetooth)
summary(df$smart_act_calling)
summary(df$smart_act_games)
summary(df$smart_act_streaming)

### Create sum score of smartphone activities
df<- df %>%
  rowwise() %>%
  dplyr::mutate(smart_act_no = sum(c_across(
    smart_act_messaging:smart_act_streaming
  ) == "Yes")) %>%
  ungroup()

summary(df$smart_act_no)
hist(df$smart_act_no)

### Tertile split No of smartphone activities
df <- df %>%
  mutate(tertile_smart_act_no = ntile(smart_act_no, 3),
         smart_act_no_ter = case_when(
           tertile_smart_act_no == 1 ~ "low",
           tertile_smart_act_no == 2 ~ "medium",
           tertile_smart_act_no == 3 ~ "high"
         ),
         smart_act_no_ter = factor(smart_act_no_ter,
                                   levels = c("low", "medium", "high")))

summary(df$smart_act_no_ter)
```

# Privacy & Trust
```{r}
## General privacy concern
summary(df$Q26)

df <- df %>% 
  dplyr::rename(privacy_num = Q26)

df <- df %>% 
  mutate(privacy_fac = factor(
    case_when(privacy_num == 1 ~ "Not concerned at all",
              privacy_num == 2 ~ "Not very concerned",
              privacy_num == 3 ~ "A little concerned",
              privacy_num == 4 ~ "Very concerned",
              .default = NA
    ),
    levels = c("Not concerned at all",
               "Not very concerned",
               "A little concerned",
               "Very concerned")
  ))

summary(df$privacy_fac)

## Perceived privacy of information
summary(as.factor(df$Q27a))
summary(df$Q27b)
summary(df$Q27c)
summary(df$Q27d)

### EFA for privacy
df_priv <- df %>% 
  select(Q27a:Q27d)
colSums(is.na(df_priv))
df_priv <- df_priv %>% 
  filter(!is.na(Q27a))
colSums(is.na(df_priv))
psych::alpha(df_priv)
KMO(df_priv)
cortest.bartlett(df_priv)
ev <- eigen(cor(df_priv))
ev$values
scree(df_priv, pc=FALSE)
fit <- factanal(df_priv, 1, rotation="promax")
print(fit, digits=2, cutoff=0.3, sort=TRUE)

### Create privacy index
df <- df %>% 
  mutate(private_index = ((Q27a + Q27b + Q27c + Q27d)/4))

summary(df$private_index)
hist(df$private_index)

### Tertile split Privacy index
df <- df %>%
  mutate(tertile_private = ntile(private_index, 3),
         private_ter = case_when(
           tertile_private == 1 ~ "low",
           tertile_private == 2 ~ "medium",
           tertile_private == 3 ~ "high"
         ),
         private_ter = factor(private_ter,
                           levels = c("low", "medium", "high")))

summary(df$private_ter)

### Build function for relabeling privacy variables
create_factor_privacy <-
  function(df, column, new_column_name) {
    df <- df %>%
      dplyr::mutate({
        {
          new_column_name
        }
      } := factor(
        case_when(.data[[column]] == 1 ~ "1 Not private at all",
                  .data[[column]] == 2 ~ "2",
                  .data[[column]] == 3 ~ "3",
                  .data[[column]] == 4 ~ "4",
                  .data[[column]] == 5 ~ "5 Very private",
                  .default = NA
        )
      ))
    return(df)
  }

### Relabel privacy variable
df <- create_factor_privacy(df, "Q27a", "private_location_fac")
df <- create_factor_privacy(df, "Q27b", "private_travel_fac")
df <- create_factor_privacy(df, "Q27c", "private_PA_fac")
df <- create_factor_privacy(df, "Q27d", "private_health_fac")

summary(df$private_location_fac)
summary(df$private_travel_fac)
summary(df$private_PA_fac)
summary(df$private_health_fac)

## Trust in various organizations
summary(df$Q28a)
summary(df$Q28b)
summary(df$Q28c)
summary(df$Q28d)
summary(df$Q28e)
summary(df$Q28f)
summary(df$Q28g)
summary(df$Q28h)

## EFA for trust (B3-B6)
df_trust <- df %>% 
  select(Q28a:Q28h)
colSums(is.na(df_trust))
df_trust <- df_trust %>% 
  filter(!is.na(Q28a))
colSums(is.na(df_trust))
psych::alpha(df_trust)
KMO(df_trust)
cortest.bartlett(df_trust)
ev <- eigen(cor(df_trust))
ev$values
scree(df_trust, pc=FALSE)
fit <- factanal(df_trust, 2, rotation="varimax")
print(fit, digits=2)

## Create two trust indexes
df <- df %>% 
  mutate(trust_pub_index = ((Q28a + Q28b + Q28c + Q28d)/4))

summary(df$trust_pub_index)
hist(df$trust_pub_index)

df <- df %>% 
  mutate(trust_priv_index = ((Q28e + Q28f + Q28g + Q28h)/4))

summary(df$trust_priv_index)
hist(df$trust_priv_index)

### Tertile split trust indexes
df <- df %>%
  mutate(tertile_trust_pub = ntile(trust_pub_index, 3),
         trust_pub_ter = case_when(
           tertile_trust_pub == 1 ~ "low",
           tertile_trust_pub == 2 ~ "medium",
           tertile_trust_pub == 3 ~ "high"
         ),
         trust_pub_ter = factor(trust_pub_ter,
                           levels = c("low", "medium", "high")))

summary(df$trust_pub_ter)

df <- df %>%
  mutate(tertile_trust_priv = ntile(trust_priv_index, 3),
         trust_priv_ter = case_when(
           tertile_trust_priv == 1 ~ "low",
           tertile_trust_priv == 2 ~ "medium",
           tertile_trust_priv == 3 ~ "high"
         ),
         trust_priv_ter = factor(trust_priv_ter,
                           levels = c("low", "medium", "high")))

summary(as.factor(df$trust_priv_ter))

### Build function for relabeling trust variables
create_factor_trust <-
  function(df, column, new_column_name) {
    df <- df %>%
      dplyr::mutate({
        {
          new_column_name
        }
      } := factor(
        case_when(.data[[column]] == 1 ~ "Don't trust at all",
                  .data[[column]] == 2 ~ "Don't trust much",
                  .data[[column]] == 3 ~ "Trust a little",
                  .data[[column]] == 4 ~ "Trust completely",
                  .default = NA
        )
      ))
    return(df)
  }

### Relabel trust variable
df <- create_factor_trust(df, "Q28a", "trust_marketresearch_fac")
df <- create_factor_trust(df, "Q28b", "trust_scientist_fac")
df <- create_factor_trust(df, "Q28c", "trust_government_fac")
df <- create_factor_trust(df, "Q28d", "trust_cbs_fac")
df <- create_factor_trust(df, "Q28e", "trust_apps_fac")
df <- create_factor_trust(df, "Q28f", "trust_onlinestores_fac")
df <- create_factor_trust(df, "Q28g", "trust_socialmedia_fac")
df <- create_factor_trust(df, "Q28h", "trust_bigtech_fac")

summary(df$trust_marketresearch_fac)
summary(df$trust_scientist_fac)
summary(df$trust_government_fac)
summary(df$trust_cbs_fac)
summary(df$trust_apps_fac)
summary(df$trust_onlinestores_fac)
summary(df$trust_socialmedia_fac)
summary(df$trust_bigtech_fac)
```

# Data Donation
```{r}
## Willingness to donate
### Reported willingness to donate Apple Health
summary(df$Q29_AH_CONSENT)

df <-
  create_factor_variable_noyes(df, "Q29_AH_CONSENT", "ah_willing")

summary(df$ah_willing)

### Reported willingness to donate Google Location History
summary(df$Q29_GLH_CONSENT)

df <-
  create_factor_variable_noyes(df, "Q29_GLH_CONSENT", "glh_willing")

summary(df$glh_willing)

### Reported willingness to donate Samsung Health
summary(df$Q29_SH_CONSENT)

df <-
  create_factor_variable_noyes(df, "Q29_SH_CONSENT", "sh_willing")

summary(df$sh_willing)

### Reported willingness to donate any data
df <- df %>%
  mutate(any_willing = factor(case_when((ah_willing == "Yes" |
                                           glh_willing == "Yes" |
                                           sh_willing == "Yes") ~ "Yes",
                                        (ah_willing == "No" |
                                           glh_willing == "No" |
                                           sh_willing == "No") ~ "No",
                                        .default = "No"
  )
  ))

summary(df$any_willing)

### Was willingness question asked?
df <- df %>%
  mutate(asked_willing = factor(
    case_when((!is.na(ah_willing) | 
                 (!is.na(glh_willing)) |
                 (!is.na(sh_willing))) ~ "Willingness question asked",
              .default = "Willingness question not asked"
    ),
    levels = c(
      "Willingness question not asked",
      "Willingness question asked"
    )
  ))

summary(df$asked_willing)

### What willingness question was asked?
df <- df %>%
  mutate(what_willing_na = factor(
    case_when((!is.na(ah_willing)) ~ "Apple Health willingness question",
              (!is.na(glh_willing)) ~ "Google Location History willingness question",
              (!is.na(sh_willing)) ~ "Samsung Health willingness question",
              .default = NA
    ),
    levels = c(
      "Apple Health willingness question",
      "Google Location History willingness question",
      "Samsung Health willingness question"
    )
  ))

summary(df$what_willing_na)

## Was DDP preview shown?
summary(df$ShowExample)

### Create function to make 1/0 variables into yes/no variables
create_factor_variable_01 <-
  function(df, column, new_column_name) {
    df <- df %>%
      dplyr::mutate({
        {
          new_column_name
        }
      } := factor(
        case_when((.data[[column]] == 0) ~ "No",
                  (.data[[column]] == 1) ~ "Yes",
                  .default = NA),
        levels = c("No",
                   "Yes")
      ))
    return(df)
  }

### Recode Show variable
df <- create_factor_variable_01(df, "ShowExample", "ShowExample")

summary(df$ShowExample)

## Started data donation
summary(df$started_donation)

df <- create_factor_variable_01(df, "started_donation", "started_donation")

summary(df$started_donation)

## Finished data donation (including declined)
summary(df$finished_donation)

df <- create_factor_variable_01(df, "finished_donation", "finished_donation")

summary(df$finished_donation)

## Was donation declined after seeing DDP?
summary(df$declined)

df <- create_factor_variable_01(df, "declined", "declined")

summary(df$declined)

## Create variable for not declined DDPs from start of donation
df <- df %>%
  mutate(DDP_available = factor(case_when((declined == "No") ~ "Yes",
                                             .default = "No"),
                                   levels = c("No", "Yes")))

summary(df$DDP_available)
```

# Open-ended question on reasons for not being willing to donate data
```{r}
## Extract responses to open-ended question for coding
reasons <- df %>% 
  select(nomem_encr, Q30)

write.table(reasons,
            file = "reasons.csv",
            row.names = FALSE,
            sep = ";",
            fileEncoding = "UTF-8")

## Add file with coded answers and merge with df
### Get coded data from https://github.com/fkeusch01/PA_data_donation/blob/main/reasons_coded.csv
reasons_coded <- read.csv(file = 'reasons_coded.csv')

df <- merge(df, reasons_coded, by = "nomem_encr")
df <- df %>% 
  mutate(Code1 = factor(Code1),
         Code2 = factor(Code2),
         Code3 = factor(Code3)) %>% 
  dplyr::rename(reason_NL = Q30.y,
         reasons_E = Q30_E)

summary(df$Code1)
summary(df$Code2)
summary(df$Code3)
```

# Clean data set
```{r}
## Drop respondents who did not get to the smartphone questions
df <- df %>% 
  filter(!is.na(smart_own))

## Select necessary variables
df <- df %>%
  select(
    nomem_encr,
    ShowExample,
    started_donation:gender,
    age_groups:lim_index,
    lim_ter:diff_index,
    diff_ter:chronic,
    bmi:days_stren_physical_act_num,
    days_stren_physical_act_ter:days_mod_physical_act_num,
    days_mod_physical_act_ter:days_walking_num,
    days_walking_ter:days_biking_num,
    days_biking_ter:days_running_num,
    days_running_ter,
    h_sedentary,
    h_sedentary_ter:smart_samsunghealth,
    smart_act_no,
    smart_act_no_ter:DDP_available,
    reason_NL:Code3
  )

# Drop unused levels in factors
df <- df %>% 
  droplevels()

## Clean work space
rm(list = setdiff(ls(), "df"))
```


# Save data
```{r}
## Save data
save.image(file = "df.RData")
```